spring.application.name=Dexcom
server.port=${APPLICATION_PORT:8999}
spring.data.mongodb.uri=${DB_HOST}
spring.data.mongodb.auto-index-creation=true
gemini.api.key=${GEMINI_KEY}
huggingface.api.token=${HF_TOKEN}
grok.api.token=${GROK_TOKEN}
